### ISSUE TITLE
Error saving profile / Error starting session

### ISSUE THREAD

**Issue by tmdag** [fleet-commander/fc-admin#231] opened 2019-03-10 06:42 UTC
Hi, 
I couldn't find any support group, so I went with github ticket.
I have FC, FreeIpa and KVM installed on same machine. I have tried creating/adding profile in FC but it was always stuck on "saving profile" indefinitely. I was hoping to get some info from journalctl but there was not much info. After days of trying, today it suddenly started working - I named new profile "test" and it did save it. (I guess it might be related to this: https://github.com/fleet-commander/fc-admin/issues/222)
Unfortunately I cannot connect to live session. I'm selecting domain - my new, fresh fedora vm installation but only what i get is not much helpful "Error starting session".

$ journalctl -xe 
```
Mar 09 22:37:07 server.mydomain.com systemd-logind[1020]: New session 2354 of user myuser.
-- Subject: A new session 2354 has been created for user myuser
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 2354 has been created for the user myuser.
-- 
-- The leading process of the session is 14835.
Mar 09 22:37:07 server.mydomain.com systemd[1]: Started Session 2354 of user myuser.
-- Subject: Unit session-2354.scope has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-2354.scope has finished starting up.
-- 
-- The start-up result is done.
Mar 09 22:37:07 server.mydomain.com sshd[14835]: pam_unix(sshd:session): session opened for user myuser by (uid=0)
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_START pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,p>
Mar 09 22:37:07 server.mydomain.com audit[14838]: CRYPTO_KEY_USER pid=14838 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:2c:b6:38:ee:ef>
Mar 09 22:37:07 server.mydomain.com audit[14838]: CRYPTO_KEY_USER pid=14838 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:00:90:a3:f9:d6:d4>
Mar 09 22:37:07 server.mydomain.com audit[14838]: CRYPTO_KEY_USER pid=14838 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:e2:98:06:0c:fb>
Mar 09 22:37:07 server.mydomain.com audit[14838]: CRED_ACQ pid=14838 uid=0 auid=1907400001 ses=2354 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix ac>
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_LOGIN pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? >
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_START pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? >
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:e2:98:06:0c:fb>
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] libvirtcontroller: Retrieving LibVirt domains
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: libvirt: Domain Config error : metadata not found: Requested metadata element is not pre>
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: libvirt: Domain Config error : metadata not found: Requested metadata element is not pre>
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] libvirtcontroller: Domains list: [{'uuid': '17c36af4-679c-4869-af53-572a1271>
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_END pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? ad>
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_LOGOUT pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=?>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=session fp=? direction=both spid=1>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:e2:98:06:0c:fb>
Mar 09 22:37:07 server.mydomain.com sshd[14835]: pam_unix(sshd:session): session closed for user myuser
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Domains retrieved: []
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Currently active temporary sessions: []
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Resetting timer for session check
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Last call time: 1552199821.755113
Mar 09 22:37:07 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Checking running sessions. Time passed: 0.00014543533325195312
Mar 09 22:37:07 server.mydomain.com audit[14835]: USER_END pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pa>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRED_DISP pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix a>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:2c:b6:38:ee:ef>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:00:90:a3:f9:d6:d4>
Mar 09 22:37:07 server.mydomain.com audit[14835]: CRYPTO_KEY_USER pid=14835 uid=0 auid=1907400001 ses=2354 msg='op=destroy kind=server fp=SHA256:c1:e2:98:06:0c:fb>
Mar 09 22:37:07 server.mydomain.com systemd-logind[1020]: Session 2354 logged out. Waiting for processes to exit.
Mar 09 22:37:07 server.mydomain.com systemd-logind[1020]: Removed session 2354.
-- Subject: Session 2354 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 2354 has been terminated.
Mar 09 22:37:08 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Last call time: 1552199821.755113
Mar 09 22:37:08 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Checking running sessions. Time passed: 1.0015714168548584
```

Also also tried renaming 'test' profile and i am getting error:
`
Error saving profile: Can not save profile.
`
FC itself, even with DEBUG mode (log_level = debug as suggested in documentation), is not showing much besides:
```
.....
Mar 09 22:34:02 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Checking running sessions. Time passed: 47.12640857696533
Mar 09 22:34:03 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Last call time: 1552199558.1947782
Mar 09 22:34:03 server.mydomain.com org.freedesktop.FleetCommander[2375]: FC: [DEBUG] Checking running sessions. Time passed: 48.12793159484863
```

**Comment by olivergs** [comment] 2019-03-11 11:00
Hi @tmdag 

The error you are experiencing about saving forever is related with #222. @stanislavlevin fixed this and we will include the patch in next release.

The error you are getting about using the KVM, the only thing I can see there is that libvirt is complaining about some metadata beign not present, but anyway it gets a VM list, so, I would need more information on what is showing at your cockpit screen to know what could be happening.

About renaming, there is no information about that in the log you pasted. When you save a profile there is a lot of information that is shown in the logs, and I can not see that in your journal. If you could test again and come back with the full log we could find the real problem.

Thanks for taking your time in using Fleet Commander

**Comment by tmdag** [comment] 2019-03-12 15:23
There is not much happening in cockpit screen but:
1. I go to "Edit" next to my 'test' profile
2. I have added one user in Users list
3. I click for "Live Session"
4. getting window "Select domain" and I am going with fresh installation of Fedora 29 that is turned off
5. 2 messages flashes through "Please wait....", "connecting...", 
6. finishing on 3rd message: Error, "Error Starting Session"
And journalctrl -xe is showing same info as one I pasted in first comment (adding new journalctl output at the bottom of this post)

```
08:18:13 ipa.myd.com audit[8553]: USER_END pid=8553 uid=0 auid=1907400001 ses=311 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux,pam_namespace,pam_keyinit,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_sss,pam_umask,pam_lastlog acct="myuser" exe="/usr/sbin/sshd" hostname=1>
08:18:13 ipa.myd.com audit[8553]: CRED_DISP pid=8553 uid=0 auid=1907400001 ses=311 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct="myuser" exe="/usr/sbin/sshd" hostname=10.0.1.10 addr=10.0.1.10 terminal=ssh res=success'
08:18:13 ipa.myd.com audit[8553]: CRYPTO_KEY_USER pid=8553 uid=0 auid=1907400001 ses=311 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8553 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:13 ipa.myd.com audit[8553]: CRYPTO_KEY_USER pid=8553 uid=0 auid=1907400001 ses=311 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8553 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:13 ipa.myd.com audit[8553]: CRYPTO_KEY_USER pid=8553 uid=0 auid=1907400001 ses=311 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8553 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:13 ipa.myd.com systemd-logind[978]: Session 311 logged out. Waiting for processes to exit.
08:18:13 ipa.myd.com systemd-logind[978]: Removed session 311.
-- Subject: Session 311 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 311 has been terminated.
08:18:13 ipa.myd.com audit[8601]: CRYPTO_KEY_USER pid=8601 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8601 suid=0  exe="/usr/sbin/sshd" hostname=? addr>
08:18:13 ipa.myd.com audit[8601]: CRYPTO_KEY_USER pid=8601 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8601 suid=0  exe="/usr/sbin/sshd" hostname=? addr>
08:18:13 ipa.myd.com audit[8601]: CRYPTO_KEY_USER pid=8601 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8601 suid=0  exe="/usr/sbin/sshd" hostname=? addr>
08:18:13 ipa.myd.com audit[8600]: CRYPTO_SESSION pid=8600 uid=0 auid=4294967295 ses=4294967295 msg='op=start direction=from-server cipher=aes256-gcm@openssh.com ksize=256 mac=<implicit> pfs=curve25519-sha256@libssh.org spid=8601 suid=74 rport=59018 laddr=10.0.1.10 lport=22  exe="/usr/sbin/sshd" >
08:18:13 ipa.myd.com audit[8600]: CRYPTO_SESSION pid=8600 uid=0 auid=4294967295 ses=4294967295 msg='op=start direction=from-client cipher=aes256-gcm@openssh.com ksize=256 mac=<implicit> pfs=curve25519-sha256@libssh.org spid=8601 suid=74 rport=59018 laddr=10.0.1.10 lport=22  exe="/usr/sbin/sshd" >
08:18:14 ipa.myd.com sshd[8600]: Authorized to myuser, krb5 principal myuser@IPA.MYD.COM (ssh_gssapi_krb5_cmdok)
08:18:14 ipa.myd.com audit[8600]: USER_ACCT pid=8600 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:accounting grantors=pam_unix,pam_sss,pam_permit acct="myuser" exe="/usr/sbin/sshd" hostname=10.0.1.10 addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com sshd[8600]: Accepted gssapi-with-mic for myuser from 10.0.1.10 port 59018 ssh2: myuser@IPA.MYD.COM
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=4294967295 ses=4294967295 msg='op=destroy kind=session fp=? direction=both spid=8601 suid=74 rport=59018 laddr=10.0.1.10 lport=22  exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=? res=success'
08:18:14 ipa.myd.com audit[8600]: CRED_ACQ pid=8600 uid=0 auid=4294967295 ses=4294967295 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct="myuser" exe="/usr/sbin/sshd" hostname=10.0.1.10 addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com systemd-logind[978]: New session 312 of user myuser.
-- Subject: A new session 312 has been created for user myuser
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A new session with the ID 312 has been created for the user myuser.
-- 
-- The leading process of the session is 8600.
08:18:14 ipa.myd.com systemd[1]: Started Session 312 of user myuser.
-- Subject: Unit session-312.scope has finished start-up
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- 
-- Unit session-312.scope has finished starting up.
-- 
-- The start-up result is done.
08:18:14 ipa.myd.com sshd[8600]: pam_unix(sshd:session): session opened for user myuser by (uid=0)
08:18:14 ipa.myd.com audit[8600]: USER_START pid=8600 uid=0 auid=1907400001 ses=312 msg='op=PAM:session_open grantors=pam_selinux,pam_loginuid,pam_selinux,pam_namespace,pam_keyinit,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_sss,pam_umask,pam_lastlog acct="myuser" exe="/usr/sbin/sshd" hostname=>
08:18:14 ipa.myd.com audit[8603]: CRYPTO_KEY_USER pid=8603 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8603 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com audit[8603]: CRYPTO_KEY_USER pid=8603 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8603 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com audit[8603]: CRYPTO_KEY_USER pid=8603 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8603 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com audit[8603]: CRED_ACQ pid=8603 uid=0 auid=1907400001 ses=312 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct="myuser" exe="/usr/sbin/sshd" hostname=10.0.1.10 addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: USER_LOGIN pid=8600 uid=0 auid=1907400001 ses=312 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: USER_START pid=8600 uid=0 auid=1907400001 ses=312 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8604 suid=1907400001  exe="/usr/sbin/sshd" hostname=? ad>
08:18:14 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [ERROR] virDomainCreateXML() argument 2 must be str or None, not bytes
08:18:14 ipa.myd.com sshd[8603]: Received disconnect from 10.0.1.10 port 59018:11: disconnected by user
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=session fp=? direction=both spid=8603 suid=1907400001 rport=59018 laddr=10.0.1.10 lport=22  exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=? res=success'
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8603 suid=1907400001  exe="/usr/sbin/sshd" hostname=? ad>
08:18:14 ipa.myd.com sshd[8603]: Disconnected from user myuser 10.0.1.10 port 59018
08:18:14 ipa.myd.com sshd[8600]: pam_unix(sshd:session): session closed for user myuser
08:18:14 ipa.myd.com audit[8600]: USER_END pid=8600 uid=0 auid=1907400001 ses=312 msg='op=PAM:session_close grantors=pam_selinux,pam_loginuid,pam_selinux,pam_namespace,pam_keyinit,pam_keyinit,pam_limits,pam_systemd,pam_unix,pam_sss,pam_umask,pam_lastlog acct="myuser" exe="/usr/sbin/sshd" hostname=1>
08:18:14 ipa.myd.com audit[8600]: CRED_DISP pid=8600 uid=0 auid=1907400001 ses=312 msg='op=PAM:setcred grantors=pam_env,pam_localuser,pam_unix acct="myuser" exe="/usr/sbin/sshd" hostname=10.0.1.10 addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: USER_END pid=8600 uid=0 auid=1907400001 ses=312 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: USER_LOGOUT pid=8600 uid=0 auid=1907400001 ses=312 msg='op=login id=1907400001 exe="/usr/sbin/sshd" hostname=? addr=10.0.1.10 terminal=ssh res=success'
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8600 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8600 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com audit[8600]: CRYPTO_KEY_USER pid=8600 uid=0 auid=1907400001 ses=312 msg='op=destroy kind=server fp=SHA256:xx:xx:xx:xx:xx direction=? spid=8600 suid=0  exe="/usr/sbin/sshd" hostname=? addr=? term>
08:18:14 ipa.myd.com systemd-logind[978]: Session 312 logged out. Waiting for processes to exit.
08:18:14 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:14 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 20.716665506362915
08:18:14 ipa.myd.com systemd-logind[978]: Removed session 312.
-- Subject: Session 312 has been terminated
-- Defined-By: systemd
-- Support: https://lists.freedesktop.org/mailman/listinfo/systemd-devel
-- Documentation: https://www.freedesktop.org/wiki/Software/systemd/multiseat
-- 
-- A session with the ID 312 has been terminated.
08:18:15 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:15 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 21.71811842918396
08:18:16 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:16 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 22.719544410705566
08:18:17 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:17 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 23.72103190422058
08:18:18 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:18 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 24.722185373306274
08:18:19 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Last call time: 1552403893.3277297
08:18:19 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Checking running sessions. Time passed: 25.72356104850769
```

When I've tried again, after clicking "Live session" i am getting "error getting domain list", it works if i click few times.

Thank you for your time and help!

**Comment by olivergs** [comment] 2019-03-12 15:42
Maybe this line of the new log you posted is the answer:

08:18:14 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [ERROR] virDomainCreateXML() argument 2 must be str or None

Seems your libvirt library is having problems to create the temporary VM FC is creating when in live session.

Can you please specify the system where FC is running and the one where libvirt is being used to run  the VM?

Also would be good to know the exact version of libvirt and kvm you are using.

Thanks

**Comment by stanislavlevin** [comment] 2019-03-12 17:18
Hi @tmdag , this error happens in FC 0.12.1 and was fixed in #209 .
I faced the same issue on Fedora29 and applied that patch for myself.
But actually, FC 0.14.0 has already landed.

**Comment by stanislavlevin** [comment] 2019-03-12 20:06
> Also also tried renaming 'test' profile and i am getting error:
> `Error saving profile: Can not save profile.`

BTW https://github.com/abbra/freeipa-desktop-profile/issues/11

**Comment by tmdag** [comment] 2019-03-13 02:20
FC and VM is on same machine:

4.20.13-200.fc29.x86_64
libvirt-4.7.0-1.fc29.x86_64
fleet-commander-admin-0.14.0-2.fc29.noarch

**Comment by olivergs** [comment] 2019-03-13 23:42
Well, FC connects to remote libvirt using ssh protocol, not TCP. The problem here and right now is that it is trying to execute very extrange commands:

19:22:23 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [DEBUG] Getting domain try 2: Error connecting to libvirt host: Error executing remote command: b'                 __                                                       \n        _____   / /_____ ___  ________  ______   _____  ___>
19:22:23 ipa.myd.com org.freedesktop.FleetCommander[5397]: FC: [ERROR] Error retrieving domains Error connecting to libvirt host: Error executing remote command: b'                 __                                                       \n        _____   / /_____ ___  ________  ______   _____  >

I do not know where that commands come from. Seems like there is a problem in pasting the logs (Of course there are not any commands like that in FC source).

I will try to test libvirt connection with your versions and try to reproduce the error so we can find the reason it is failing. Please, be patient as I'm trying to finish the FC client matching release for 0.14.0 Admin at the same time.

Thanks for the info.

**Comment by tmdag** [comment] 2019-03-14 05:08
> Seems like there is a problem in pasting the logs 

That was literally an output of journalctrl. I was wondering about it as well :)

Just tried once again second ago:

```
Mar 13 22:07:43 tmserver.home.iblvfx.com audit[24832]: CRYPTO_KEY_USER pid=24832 uid=0 auid=1907400001 ses=615 msg='op=destroy kind=server fp=SHA256:c1:e2:98:06:0c:fb:ff:74:89:79:a6:1c:9f:ed:2b:46:32:c3:36:c3:c3:cd:f2:c6:b0:39:43:6a:49:25:d5:d2 direction=? spid=24837 suid=1907400001  exe="/usr/sbin/sshd" hostname=?>
Mar 13 22:07:43 tmserver.home.iblvfx.com org.freedesktop.FleetCommander[7409]: FC: [DEBUG] Getting domain try 2: Error connecting to libvirt host: Error executing remote command: b'                 __                                                       \n        _____   / /_____ ___  ________  ______   _____  ___>
Mar 13 22:07:43 tmserver.home.iblvfx.com org.freedesktop.FleetCommander[7409]: FC: [ERROR] Error retrieving domains Error connecting to libvirt host: Error executing remote command: b'                 __                                                       \n        _____   / /_____ ___  ________  ______   _____  >
Mar 13 22:07:43 tmserver.home.iblvfx.com org.freedesktop.FleetCommander[7409]: FC: [DEBUG] Last call time: 1552540063.0799735
Mar 13 22:07:43 tmserver.home.iblvfx.com org.freedesktop.FleetCommander[7409]: FC: [DEBUG] Checking running sessions. Time passed: 9.78315806388855

```

**Comment by tmdag** [comment] 2019-03-14 05:21
OK, That was just my sshd banner displaying there :) But issue is still there. Disabled banner just in case.

**Comment by olivergs** [comment] 2019-03-14 10:10
Now the error is a bit more clear:

```
:02 ipa.myd.com org.freedesktop.FleetCommander[7409]: FC: [DEBUG] Getting domain try 2: Error connecting to libvirt host: Error executing remote command: b'Ambiguous output redirect.\n'
:02 ipa.myd.com org.freedesktop.FleetCommander[7409]: FC: [ERROR] Error retrieving domains Error connecting to libvirt host: Error executing remote command: b'Ambiguous output redirect.\n'
```

After having a read to this forum: https://www.unix.com/shell-programming-and-scripting/96012-ambiguous-output-redirect-error.html

I suspect it can be related to a customization in the shell for the user you have configured in fleet commander for libvirt stuff.

FC uses some shell commands to ensure known hosts etc works, so it seems the problem is it expects bash as shell, and not csh or tsh. Could you confirm if this is the case?

If it is, please tell us to open an issue for making FC more "shell agnostic".

**Comment by tmdag** [comment] 2019-03-14 15:07
yes, I can confirm. My ipa user default shell is tcsh

**Comment by olivergs** [comment] 2019-03-14 16:29
Ok. Could you try using bash for now, until we study the way to do this in
a more compatible way?

Thanks

**Comment by olivergs** [comment] 2020-05-11 10:01
Closing this issue due to inactivity and the fact we found the root of the problem and already have an issue for that.

Thanks for reporting!

**Closed by olivergs** 2020-05-11 10:01 UTC

**Comment by aruiz** [comment] 2020-05-11 11:43
> Closing this issue due to inactivity and the fact we found the root of the problem and already have an issue for that.
> 
> Thanks for reporting!

If there is another issue we should link it here

**Comment by olivergs** [comment] 2020-05-11 11:58
![image](https://user-images.githubusercontent.com/1439905/81559267-01e6ea80-9387-11ea-879a-5811398ed2e2.png)
It is mentioned on this issue thread. Anyway, the issue is the #235.
