### ISSUE TITLE
Please stop including cockpit's deprecated bundled jquery 

### ISSUE THREAD

**Issue by martinpitt** [fleet-commander/fc-admin#165] opened 2018-02-06 18:29 UTC
This project currently uses jquery from cockpit:

     <script type="text/javascript" src="../base1/jquery.js"></script>

Cockpit's own examples and documentation included this (which got fixed now), but it's a potential breakage for any external cockpit extensions, so this needs to be cleaned up. Sorry about that!

Particularly, cockpit will update to jQuery 3.0 soon (https://github.com/cockpit-project/cockpit/pull/8505) which has quite a lot of changes, see the [upgrade guide](https://jquery.com/upgrade-guide/3.0/). Please include your own jquery copy from npmjs.org instead.

Please see https://lists.fedorahosted.org/archives/list/cockpit-devel@lists.fedorahosted.org/thread/TDBKI4372I4ZPGQFCZB377DX2QG2YDDY/ for more information.

**Comment by olivergs** [comment] 2018-02-06 19:03
Thanks for the advice Martin. Will check this all and prepare a patch ASAP

**Comment by martinpitt** [comment] 2018-02-23 08:51
FYI, yesterday we switched Cockpit maser to jQuery 3. This will be released on March 7.

**Comment by olivergs** [comment] 2018-02-23 09:26
Thank you Martin. Yesterday I finished with chromium/chrome support and I wanted to take today to fix this and some other things.

**Comment by aruiz** [comment] 2018-02-23 16:00
@martinpitt are you going to backport this change to the current Fedora versions being supported?

**Comment by martinpitt** [comment] 2018-02-23 16:06
@aruiz: It will eventually land in Fedora 27 (that's where we upload new versions to right now), but not to earlier ones.

**Comment by aruiz** [comment] 2018-02-23 16:08
It'd be good to clatify this type of policy for plugins, breaking things like this is not ideal and enforcing each plugin to distribute it's own jquery version is also not ideal from a security POV.

**Comment by olivergs** [comment] 2018-02-26 11:12
This should be fixed by PR #171

**Comment by martinpitt** [comment] 2018-02-26 11:40
Nice, thanks! Also good to know that fc works with jQuery 3. However, this is not a given, hence it's not generally safe to rely on an external jquery whose version you don't control. I know, this sucks, but that's the JS world I'm afraid :-/

**Comment by olivergs** [comment] 2018-02-26 11:46
Anyway our idea is to revisit the UI as soon as we finish support for some of the features we have in the roadmap and at that moment I will probably refactor the whole pugin UI part. But for now, the problem is fixed and working.

**Closed by olivergs** 2018-02-26 11:46 UTC
